export const PersistenceKey = {
    LOCALE: btoa('LOCALE'),
    ACCESS_TOKEN: btoa('ACCESS_TOKEN'),
    AUTHENTICATED: btoa('AUTHENTICATED'),
    VISITED: btoa('VISITED'),
    REFRESH_TOKEN: btoa('REFRESH_TOKEN'),
    TOKEN_EXPIRES_AT: btoa('TOKEN_EXPIRES_AT'),
    USER_DETAILS: btoa('USER_DETAILS'),
    REGISTRATION_EMAIL: btoa('REGISTRATION_EMAIL'),
    COURSE_WIP: btoa('COURSE_WIP'),
    PRIVILEGES: btoa('PRIVILEGES'),
    SERVER_SESSION: btoa('SERVER_SESSION'),
    XSRF_TOKEN: btoa("XSRF-TOKEN"),
    laravel_session: btoa("laravel_session"),
    SERVER_HOME: btoa("BASE_URI"),
}
