export const REFS = {
    DASHBOARD: 'DASHBOARD',
    HOME: 'HOME',
    SELL: 'SELL',
    MAKE_SALE: 'MAKE_SALE',
    PURCHASE: 'PURCHASE',
    PRODUCTS: 'PRODUCTS',
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    CREATE_CATEGORY: 'CREATE_CATEGORY',
    CATEGORIES: 'CATEGORIES',
    REPORTS: 'REPORTS',
    USERS: 'USERS',
    PRODUCT_SUMMARY: 'PRODUCT_SUMMARY'
}

export const LINKS = {
    DASHBOARD: '/dashboard',
    HOME: '/'
}